common/models/Logo.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "logo".
 *
 * @property int $id
 * @property string $image
 * @property string $copyright
 */

class Logo extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public $path = 'images/logo/';

    public static function tableName()
    {
        return 'logo';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['copyright'], 'required'],
            [['copyright'], 'string', 'max' => 255],
            [['image'], 'file', 'extensions' => 'png,jpg'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'image' => 'Логотип',
            'copyright' => 'Копирайт',
        ];
    }


    public function getImage(){
        return '/backend/web/'.$this->path.''.$this->image;
    }

    public static function getContent(){
        return Logo::find()->one();
    }

}

backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use common\models\Admission;
use common\models\Products;
use common\models\Review;
use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post', 'get'],
                ],
            ],
        ];
    }



    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {

        if (Yii::$app->user->isGuest) {
            return $this->redirect('/admin/site/login')->send();
        }elseif(Yii::$app->user->identity->role == null){
            Yii::$app->user->logout();
            return $this->redirect('/admin/site/login')->send();
        }

        Yii::$app->view->params['admission'] = Admission::findOne(["user_id" => Yii::$app->user->id]);

        Yii::$app->view->params['feedback'] = Review::findAll(['isRead' => 0]);

        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) { return $this->goHome();}

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/SiteController.php
<?php

namespace frontend\controllers;

use common\models\Advantages;
use common\models\Banner;
use common\models\CatalogProducts;
use common\models\Filial;
use common\models\FilialProduct;
use common\models\Mainsub;
use common\models\Menu;
use common\models\Products;
use common\models\Slider;
use Yii;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\web\NotFoundHttpException;


/**
 * Site controller
 */
class SiteController extends FrontendController
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post', 'get'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
                'foreColor' => 0xffffff,
                'offset' => 3,
                'backColor' =>  0x4a5e68,
                'fontFile'  => '@frontend/web/fonts/Century Gothic.ttf',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */

    public function actionIndex()
    {
        $titles = Mainsub::getAll();
        $banner = Banner::getAll();
        $filial = Filial::getAll();
        $topMonthProducts = Products::getSomeTopMonthProducts(0);
        $hitProducts = Products::getSomeHitProducts(0);
        $catalog = CatalogProducts::getFirstLevel();
        $sliders = Slider::getAll();

        unset($_SESSION['hit_product_of_set']);
        unset($_SESSION['top_month_product_of_set']);
        // phpinfo();
        // die();
        return $this->render('index', compact('titles', 'banner', 'filial', 'hitProducts', 'catalog', 'topMonthProducts', 'sliders'));
    }


    public function actionIndex2($url)
    {

        $page = Menu::findOne(['url' => $url]);

        if ($page) {
            return $this->render('index2', compact('page'));
        } else {
            throw new NotFoundHttpException();
        }
    }


    public function actionLoadMoreHitProducts()
    {

        if (Yii::$app->request->isAjax) {
            if (isset($_SESSION['hit_product_of_set'])) {
                $_SESSION['hit_product_of_set'] += Products::HIT_PRODUCT_LOAD_QUANTITY;
            } else {
                $_SESSION['hit_product_of_set'] = 4;
            }

            $model = Products::getSomeHitProducts($_SESSION['hit_product_of_set']);
            $id = $_GET['id'];
            $count = 9;

            return $this->renderAjax('products', compact('model', 'id', 'count'));
        } else {
            throw new NotFoundHttpException();
        }
    }





    public function actionLoadMoreHitButton()
    {

        if (Yii::$app->request->isAjax) {
            $offSet = $_SESSION['hit_product_of_set'] + Products::HIT_PRODUCT_LOAD_QUANTITY;
            $model = Products::getSomeHitProducts($offSet);
            if (count($model) > 4) $status = 1;
            else $status = 0;

            return json_encode(['status' => $status]);
        } else {
            throw new NotFoundHttpException();
        }
    }



    public function actionLoadMoreTopMonthProducts()
    {

        if (Yii::$app->request->isAjax) {
            if (isset($_SESSION['top_month_product_of_set'])) {
                $_SESSION['top_month_product_of_set'] += Products::TOP_MONTH_PRODUCT_LOAD_QUANTITY;
            } else {
                $_SESSION['top_month_product_of_set'] = 4;
            }

            $model = Products::getSomeTopMonthProducts($_SESSION['top_month_product_of_set']);
            $id = $_GET['id'];
            $count = 9;

            return $this->renderAjax('products', compact('model', 'id', 'count'));
        } else {
            throw new NotFoundHttpException();
        }
    }



    public function actionLoadMoreTopMonthButton()
    {

        if (Yii::$app->request->isAjax) {
            $offSet = $_SESSION['top_month_product_of_set'] + Products::TOP_MONTH_PRODUCT_LOAD_QUANTITY;
            $model = Products::getSomeTopMonthProducts($offSet);
            if (count($model) > 8) $status = 1;
            else $status = 0;

            return json_encode(['status' => $status]);
        } else {
            throw new NotFoundHttpException();
        }
    }




    public function actionLoadMoreHitProductsMobile()
    {

        if (Yii::$app->request->isAjax) {
            if (isset($_SESSION['hit_product_of_set'])) {
                $_SESSION['hit_product_of_set'] += Products::HIT_PRODUCT_LOAD_QUANTITY;
            } else {
                $_SESSION['hit_product_of_set'] = 4;
            }

            $model = Products::getSomeHitProducts($_SESSION['hit_product_of_set']);
            $id = $_GET['id'];
            $count = 9;

            return $this->renderAjax('mobile_products', compact('model', 'id', 'count'));
        } else {
            throw new NotFoundHttpException();
        }
    }



    public function actionLoadMoreTopMonthProductsMobile()
    {

        if (Yii::$app->request->isAjax) {
            if (isset($_SESSION['top_month_product_of_set'])) {
                $_SESSION['top_month_product_of_set'] += Products::TOP_MONTH_PRODUCT_LOAD_QUANTITY;
            } else {
                $_SESSION['top_month_product_of_set'] = 4;
            }

            $model = Products::getSomeTopMonthProducts($_SESSION['top_month_product_of_set']);
            $id = $_GET['id'];
            $count = 9;

            return $this->renderAjax('mobile_products', compact('model', 'id', 'count'));
        } else {
            throw new NotFoundHttpException();
        }
    }

}

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = 'Не найдено (# 404)';
?>
<div class="site-error" style="height:350px;margin: 50px;">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        Страница не найдено
    </div>

    <p>
        Вышеуказанная ошибка произошла, когда веб-сервер обрабатывал ваш запрос.
    </p>
    <p>
        Пожалуйста, свяжитесь с нами, если считаете, что это ошибка сервера. Спасибо.
    </p>

</div>

frontend/views/site/index2.php
<div class="inner-page">
    <div class="container py-5 px-5 px-sm-0">
        <?= $page->content; ?>
    </div>
</div>

frontend/views/site/mobile_hit_products.php
<? $m = 0; ?>
<? foreach ($model as $v) : ?>
    <? $m++; ?>
    <? if ($m < $count) : ?>
        <div class="col-sm-12 col-md-12 col-lg-6 wow fadeInUp">
            <a href="<?=$v->getUrl();?>">
                <div class="new-item">
                    <? if ($v->discount) : ?>
                        <div class="sale">
                            <img src="/images/sale.svg" style="height: auto;"/>
                            <div class="sale" style="left: -7px;top: 10px;">
                                <p>-<?= $v->discount ?>%</p>
                            </div>
                        </div>
                    <? endif; ?>
                    <div class="image">
                        <img src="<?=$v->getImage();?>" >
                    </div>
                    <div class="text-block">
                        <div class="name">
                            <p><?= $v->name ?></p>
                        </div>
                        <div class="status">

                            <p><img src="/images/ok.png" alt="">Есть в наличии</p>

                            <? if (Yii::$app->user->isGuest) : ?><a href="#"><i class="fas fa-heart favorite" onclick="locateToSignIn()"></i></a>
                            <? else : ?><i class="fas fa-heart like-active favorites <?= $v->getFavoriteStatus() ? 'favorites-active' : ''; ?>" data-id="<?= $v->id; ?>"></i>
                            <? endif; ?>
                        </div>
                        <div class="flex-one">
                            <div class="price">
                                <? if ($v->discount):?>
                                    <p><?= number_format($v->oldPrice, 0, '', ' '); ?></p>
                                <? endif;?>
                                <span class="gradient-text"><?= number_format($v->calculatePrice, 0, '', ' '); ?> </span> тг
                            </div>
                            <div class="news-basket-button">
                                <button class="btn-in-basket" data-id="<?= $v->id; ?>" data-slider-id="<?= $id; ?>">
                                    <img src="/images/light-basket.png" alt="">В корзину</button>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
        </div>
    <? endif; ?>
<? endforeach; ?>

frontend/views/site/mobile_products.php
<div class="row">
<? $m = 0; ?>
<? foreach ($model as $v) : ?>
    <? $m++; ?>
    <? if ($m < $count) : ?>

        <?=$this->render('/partials/mobile_product', ['product' => $v, 'id' => $id, 'class' => 'col-lg-3 col-md-6 col-sm-12 col-6 mob_p wow fadeInUp']);?>

    <? endif; ?>
<? endforeach; ?>
</div>

frontend/views/site/mobile_top_month_products.php
<? $m = 0; ?>
<? foreach ($model as $v) : ?>
    <? $m++; ?>
    <? if ($m < $count) : ?>

        <div class="top-sale-item">
            <? if ($v->isHit == 1) : ?>
                <div class="hit">
                    <img src="/images/hit.png" alt="">
                </div>
            <? endif; ?>
            <? if ($v->discount) : ?>
                <div class="sale">
                    <img src="/images/sale.svg" style="height: auto;" />
                    <div class="sale" >
                        <p>-<?= $v->discount ?>%</p>
                    </div>
                </div>
            <? endif; ?>
            <a href="<?=$v->getUrl();?>">
                <img src="<?=$v->getImage();?>" >
            </a>
            <div class="name">
                <p><?= $v->name ?></p>
            </div>
            <div class="price">
                <? if ($v->discount):?>
                    <p><?= number_format($v->oldPrice, 0, '', ' '); ?></p>
                <? endif;?>
                <span class="gradient-text"><?= number_format($v->calculatePrice, 0, '', ' '); ?> </span> тг
            </div>
            <div class="basket-button">
                <button class="btn-in-basket" data-id="<?= $v->id; ?>" data-slider-id="<?= $id; ?>">
                    <img src="/images/light-basket.png" alt="">В корзину</button>
            </div>
        </div>

    <? endif; ?>
<? endforeach; ?>

frontend/views/site/products.php
<? $m = 0; ?>
<? foreach ($model as $v) : ?>
    <? $m++; ?>
    <? if ($m < $count) : ?>

        <?=$this->render('/partials/desktop_product', ['product' => $v, 'id' => $id , 'class' => 'col-lg-3 col-md-6 col-sm-12 wow fadeInUp']);?>

    <? endif; ?>
<? endforeach; ?>